### ISSUE TITLE
Type mismatch when trying to get LXCs' VMID

### ISSUE THREAD

**Issue by fzsombor** [Starttoaster/proxmox-exporter#47] opened 2024-07-27 16:44 UTC
Hi there,

trying to get this exporter working but it seems like something is not right in the API output. I've no time atm to check at the code, but this is what I get:

```

06:32:58 root@pve proxmox-exporter ±|main ✗|→ ./proxmox-exporter --proxmox-endpoints "https://192.168.redacted:8006" --proxmox-token-id 'redacted' --proxmox-token "redacted" --proxmox-api-insecure=true --log-level debug
time=2024-07-27T18:33:05.318+02:00 level=DEBUG msg="Creating Proxmox client" endpoint=https://192.168.redacted:8006 hostname=192.168.redaxted
time=2024-07-27T18:33:05.333+02:00 level=INFO msg="Starting server" port=8080
time=2024-07-27T18:33:52.244+02:00 level=DEBUG msg="banning client" name=192.168.redacted duration=1m0s
time=2024-07-27T18:33:52.244+02:00 level=ERROR msg="failed making request to get node LXCs" node=pve error="json: cannot unmarshal number into Go struct field GetNodeLxcData.data.vmid of type string"
time=2024-07-27T18:33:52.244+02:00 level=ERROR msg="failed making request to get node storage" node=pve error="request to get node storage was not successful. It's possible all clients are banned"
time=2024-07-27T18:33:52.244+02:00 level=ERROR msg="failed making request to get node disks" node=pve error="request to get node disks was not successful. It's possible all clients are banned"
time=2024-07-27T18:33:52.244+02:00 level=ERROR msg="failed making request to get node certificates" node=pve error="request to get node certificates was not successful. It's possible all clients are banned"
time=2024-07-27T18:33:52.244+02:00 level=ERROR msg="failed making request to get node status" node=pve error="request to get node status was not successful. It's possible all clients are banned"
time=2024-07-27T18:33:52.244+02:00 level=DEBUG msg="finished requests for node data" node=pve
```

PVE version is 8.2.4.
Example snippet from PVE API output `api2/json/nodes/pve/lxc`
```   
"data": [
        {
          "diskwrite": 723009536,
          "cpu": 0.0122850262889966,
          "netin": 933275926,
          "mem": 136007680,
          "pid": 12487,
          "swap": 30760960,
          "uptime": 1380430,
          "vmid": 116,
          "type": "lxc",
          "maxmem": 1073741824,
          "status": "running",
          "maxdisk": 4143677440,
          "tags": "proxmox-helper-scripts",
          "diskread": 1715552256,
          "maxswap": 536870912,
          "cpus": 1,
          "netout": 162448553,
          "disk": 1809444864,
          "name": "octoprint"
    }, ...
```

Thanks!

**Comment by Starttoaster** [comment] 2024-07-29 01:18
Hey! Thanks for the Issue. That is interesting, I'm a bit behind on updates in my cluster (8.1.4 here) and can't reproduce this on my version. But tomorrow I can update and see if I can reproduce in the latest version. Odd that Proxmox would switch from a string to integer in a minor release though, if that's what happened.

**Comment by Starttoaster** [comment] 2024-08-07 18:24
Can confirm on PVE update to 8.2.4 that LXC VMIDs appeared to change to an integer, whereas they used to be a string. Which I have opinions about 😂 Writing a stable API is really difficult for some dev teams. Anyway, I'll get that fixed in the Proxmox API library, and then put out an update in this proxmox-exporter to address it. Thanks for the Issue!

**Closed** 2024-08-08 02:47 UTC

**Comment by Starttoaster** [comment] 2024-08-08 02:54
The latest release of the exporter solves this :) Please reach out if you find any other issues!!
